import { StyleSheet } from "react-native";

export const presentationStyles = StyleSheet.create({
  loadingContainer: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "black",
    zIndex: 10,
  },
  webview: {
    flex: 1,
    pointerEvents: "auto",
  },
  jsonCacheBanner: {
    position: "absolute",
    top: 12,
    right: 12,
    maxWidth: "70%",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    zIndex: 20,
  },
  jsonCacheBannerInfo: {
    backgroundColor: "#003060",
    borderColor: "#003060",
  },
  jsonCacheBannerSuccess: {
    backgroundColor: "#003060",
    borderColor: "#003060",
  },
  jsonCacheBannerError: {
    backgroundColor: "#003060",
    borderColor: "#003060",
  },
  jsonCacheBannerText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: "Georgia",
    textAlign: "left",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  alertBox: {
    width: "90%",
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 10,
    elevation: 5,
    maxHeight: "80%",
  },
  closeButton: {
    position: "absolute",
    top: 10,
    left: 10,
    zIndex: 1,
    backgroundColor: "#DDDDDD",
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
  },
  closeButtonText: {
    fontSize: 18,
    color: "#333333",
    fontWeight: "bold",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  content: {
    paddingBottom: 20,
    marginTop: 10,
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
});
