export const copticSaintFeasts = [
    { date: "Tout 1", feast: "Feast of El-Nayrouz (Beginning of the Blessed Coptic Year).", priority: 5, type: ["Feast"]},
    { date: "Tout 1", feast: "The Martyrdom of St. Bartholomew, the Apostle.", priority: 5, type: ["Apostle" , "Martyr"], saintName: "Any Apostle"},
    { date: "Tout 1", feast: "The Departure of St. Melyos (Milius), the Third Pope of Alexandria.", priority: 5, type: ["Pope","Saint"]},
    { date: "Tout 2", feast: "The Martyrdom of St. John the Baptist.", priority: 5, type: ["Heavenly"], saintName: "St. John The Baptist"},
    { date: "Tout 2", feast: "The Martyrdom of St. Dasya the Soldier.", priority: 5, type: ["Martyr"]},
    { date: "Tout 3", feast: "A Council held in the city of Alexandria.", priority: 5, type: ["Event"]},
    { date: "Tout 3", feast: "A Great Earthquake took place in Cairo and Most of the Egyptian Cities.", priority: 5, type: ["Event"]},
    { date: "Tout 4", feast: "The Departure of St. Macarius, 69th Pope of Alexandria", priority: 5, type: ["Pope","Saint"]},
    { date: "Tout 5", feast: "The Martyrdom of Saint Sophia", priority: 5, type: ["Female Martyr"]},
    { date: "Tout 6", feast: "The Departure of Isaiah the Prophet.", priority: 5, type: ["Prophet", "Saint"]},
    { date: "Tout 6", feast: "The Martyrdom of Saint Basilissa.", priority: 5, type:["Female Martyr"] },
    { date: "Tout 7", feast: "The Departure of St. Dioscorus, 25th Pope of Alexandria.", priority: 5, type: ["Pope","Saint"]},
    { date: "Tout 7", feast: "The Martyrdom of Sts. Agathon, Peter, John, Amun and Amuna and Their Mother, Rebecca.", priority: 5, type: ["Martyr"]},
    { date: "Tout 7", feast: "The Departure of St. Severianus, Bishop of Gabala.", priority: 5, type: ["Saint"]},
    { date: "Tout 8", feast: "The Martyrdom of Zacharias the Prophet.", priority: 5, type: ["Prophet","Martyr"]},
    { date: "Tout 8", feast: "The Departure of Moses the Prophet.", priority: 5, type: ["Prophet","Saint"]},
    { date: "Tout 8", feast: "The Martyrdom of St. Dimides (Diomede).", priority: 5, type: ["Martyr"]},
    { date: "Tout 9", feast: "The Martyrdom of St. Pisora the Bishop", priority: 5, type: ["Martyr"]},
    { date: "Tout 10", feast: "The Martyrdom of Saint Matruna.", priority: 5, type: ["Female Martyr"]},
    { date: "Tout 10", feast: "The Commemoration of Sts. Basin and Her Children.", priority: 5, type: ["Martyr"]},
    { date: "Tout 11", feast: "The Martyrdom of Saint Basilides (Wasilides)", priority: 5, type: ["Martyr"]},
    { date: "Tout 12", feast: "The Assembly of the Third Ecumenical Council at Ephesus to Judge Nestorius, Archbishop of Constantinople.", priority: 5, type: ["Event"]}, 
    { date: "Tout 12", feast: "The Translocation of the Relics of Sts. Clemus (Aklimos) and His Companions.", priority: 5, type: ["Martyr"]},
    { date: "Tout 13", feast: "The Departure of Pope Mattheos II, 90th Patriarch of the See of St. Mark.", priority: 5, type: ["Pope","Saint"]},
    { date: "Tout 13", feast: "The Commemoration of the Miracle performed by St. Basilius (Basil), Bishop of Caesarea, Cappadocia.", priority: 5, type: ["Event"]},       
    { date: "Tout 14", feast: "The Departure of St. Agathon the Stylite", priority: 5, type: ["Saint"]},
    { date: "Tout 15", feast: "Translocation of the Body of St. Stephen the Archdeacon", priority: 5, type: ["Martyr"], saintName: "St. Stephen The Archdeacon"},
    { date: "Tout 16", feast: "The Commemoration of the Consecration of the Sanctuaries of the church of Resurrection in Jerusalem.", priority: 5, type: ["Event"]},      
    { date: "Tout 16", feast: "The Translocation of the Relics of St. John Chrysostom (of the Golden Mouth).", priority: 5, type: ["Saint"]},
    { date: "Tout 17", feast: "The Feast of the Consecration of the Church of the Honorable Cross.", priority: 5, type: ["Feast"]},
    { date: "Tout 17", feast: "The Departure of St. Theognosta.", priority: 5, type: ["Saint"]},
    { date: "Tout 18", feast: "The Martyrdom of St. Prophorius (Porphyrius).", priority: 5, type: ["Martyr"]},
    { date: "Tout 18", feast: "The Commemoration of Stephen the Priest, and St. Niceta (Niketa) the Martyr.", priority: 5, type: ["Martyr"]},
    { date: "Tout 19", feast: "The Commemoration of St. Gregory, Patriarch of the Armenians", priority: 5, type: ["Patriarch","Saint"]},
    { date: "Tout 20", feast: "The Departure of pope Athanasius the Second, the Twenty-Eighth Patriarch of the See of St. Mark.", priority: 5, type: ["Pope","Saint"]},
    { date: "Tout 20", feast: "The Martyrdom of St. Melitina the Virgin.", priority: 5, type: ["Female Martyr"]},
    { date: "Tout 20", feast: "The Departure of St. Theopista.", priority: 5, type: ["Female Saint"]},
    { date: "Tout 21", feast: "The Commemoration of the Virgin St. Mary, the Theotokos.", priority: 5, type: ["Theotokos"]},
    { date: "Tout 21", feast: "The Martyrdom of St. Cyprian (Cyprianus) and St. Justina.", priority: 5, type: ["Martyr"]},
    { date: "Tout 22", feast: "The Martyrdom of Saints Cotylas (Kobtlas) and Axoua, his Sister, and Tatas, his Friend.", priority: 5, type: ["Martyr"]},
    { date: "Tout 22", feast: "The Martyrdom of St. Julius of Aqfahs (El-Akfehasi), the Writer of the Biography of Martyrs.", priority: 5, type: ["Martyr"]},
    { date: "Tout 23", feast: "The Martyrdom of Sts. Eunapios (Onanius) and Andrew.", priority: 5, type: ["Martyr"]},
    { date: "Tout 23", feast: "The Commemoration of the Martyrdom of St. Thecla.", priority: 5, type:["Female Martyr"]},
    { date: "Tout 23", feast: "The Re-Opening of the church of the Virgin in Haret El-Rum.", priority: 5, type: ["Theotokos"]},
    { date: "Tout 24", feast: "The Departure of St. Gregory the Ascetic.", priority: 5, type: ["Saint"]},
    { date: "Tout 24", feast: "The Martyrdom of St. Quadratus, One of the Seventy Disciples.", priority: 5, type: ["Martyr","Disciple"]},
    { date: "Tout 25", feast: "The Departure of Jonah, the Great Prophet", priority: 5, type: ["Prophet","Saint"]},
    { date: "Tout 26", feast: "The Angels' Annunciation of John the Baptist to Zacharias", priority: 5, type: ["Heavenly"], saintName: "St. John The Baptist"},
    { date: "Tout 27", feast: "The Martyrdom of St. Eustathius and His Two Sons", priority: 5, type: ["Martyr"]},
    { date: "Tout 28", feast: "The Martyrdom of Saints Abadir (Apater) and Eraee (Herai), His Sister", priority: 5, type: ["Martyr"]},
    { date: "Tout 29", feast: "The Martyrdom of St. Arbsima (Repsima) the Virgin and Her Sisters the Virgins", priority: 5, type:["Female Martyr"]},
    { date: "Tout 30", feast: "The Commemoration of the Miracle that God Performed for St. Athanasius the Apostolic", priority: 5, type: ["Saint", "Pope","Event"], saintName: "St. Athanasius The Apostolic"},
    { date: "Baba 1", feast: "The Martyrdom of Saint Anastasia", priority: 5, type:["Female Martyr"]},
    { date: "Baba 2", feast: "The Coming of Saint Severus, Patriarch of Antioch, to Egypt", priority: 5, type: ["Event"], saintName: "St. Severus of Antioch"}, 
    { date: "Baba 3", feast: "The Departure of St. Simon II, 51st Pope of the See of St. Mark.", priority: 5, type: ["Pope","Saint"]},
    { date: "Baba 3", feast: "The Martyrdom of St. John the Soldier.", priority: 5, type: ["Martyr"]},
    { date: "Baba 4", feast: "The Martyrdom of St. Bacchus, the Friend of St. Sergius", priority: 5, type: ["Martyr"], saintName: "Sts. Sergius & Bacchus"},
    { date: "Baba 5", feast: "The Martyrdom of St. Paul, Patriarch of Constantinople", priority: 5, type: ["Patriarch","Martyr"]},
    { date: "Baba 6", feast: "The Departure of the Righteous Hannah, the Prophetess Mother of Samuel, the Prophet", priority: 5, type: ["Prophet","Saint"]},
    { date: "Baba 7", feast: "The Departure of St. Paul of Tamouh", priority: 5, type: ["Saint"], saintName: "St. Paul of Tamouh"},
    { date: "Baba 8", feast: "The Martyrdom of St. Matra.", priority: 5},
    { date: "Baba 8", feast: "The Martyrdom of the Saints Abba Hor, Tosia (Susanna) and Her Children, and Abba Agathon, the Hermit.", priority: 5},      
    { date: "Baba 9", feast: "The Departure of St. Eumenius, the Seventh Pope of the See of St. Mark.", priority: 5},
    { date: "Baba 9", feast: "The Eclipse of the Sun in the Year 958 A.M.", priority: 5},
    { date: "Baba 9", feast: "The Commemoration of St. Simon (Simeon) the Bishop.", priority: 5},
    { date: "Baba 10", feast: "The Martyrdom of St. Sergius, the Friend of St. Bacchus", priority: 5},
    { date: "Baba 11", feast: "The Departure of St. James, Patriarch of Antioch.", priority: 5},
    { date: "Baba 11", feast: "The Departure of St. Pelagia.", priority: 5},
    { date: "Baba 12", feast: "The Departure of Abba Demetrius I, 12th Pope of Alexandria.", priority: 5},
    { date: "Baba 12", feast: "The Commemoration of the Archangel Michael.", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Baba 12", feast: "The Martyrdom of St. Matthew the Evangelist.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Baba 13", feast: "The Departure of Saint Zacharias, the Monk", priority: 5},
    { date: "Baba 14", feast: "The Departure of St. Philip, One of the Seven Deacons", priority: 5},
    { date: "Baba 15", feast: "The Martyrdom of Saint Panteleimon, the Physician", priority: 5},
    { date: "Baba 16", feast: "The Departure of St. Agathon, 39th Pope of Alexandria.", priority: 5},
    { date: "Baba 16", feast: "The Commemoration of the Sts. Carpus, Apollos (Papylus) and Peter.", priority: 5},
    { date: "Baba 17", feast: "The Departure of St. Dioscorus II 31st Pope of Alexandria", priority: 5},
    { date: "Baba 18", feast: "The Departure of the Honorable Father Saint Theophilus 23rd Pope of Alexandria", priority: 5},
    { date: "Baba 19", feast: "The Assembly of the Council of Antioch against Paul of Samosata.", priority: 5},
    { date: "Baba 19", feast: "The Martyrdom of Sts. Theophilus and His Wife in Fayyum.", priority: 5},
    { date: "Baba 20", feast: "The Departure of the Great St. John Colobos (the Short)", priority: 5, type: ["Saint"], saintName: "St. John the Short"},  
    { date: "Baba 21", feast: "The Commemoration of the Theotokos.", priority: 5},
    { date: "Baba 21", feast: "The Commemoration of the Relocation of the Body of Lazarus.", priority: 5},
    { date: "Baba 21", feast: "The Departure of Joel the Prophet.", priority: 5},
    { date: "Baba 21", feast: "The Departure of St. Freig (Abba Tegi, Anba Roweiss).", priority: 5, type: ["Saint"], saintName: "St. Freig (Abba Tegi, Anba Roweiss)"}, 
    { date: "Baba 22", feast: "The Martyrdom of Saint Luke the Evangelist", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Baba 23", feast: "The Departure of St. Yousab, 52nd Pope of Alexandria.", priority: 5},
    { date: "Baba 23", feast: "The Martyrdom of St. Dionysius, Bishop of Corinth.", priority: 5},
    { date: "Baba 24", feast: "The Departure of the Righteous Father Abba Hilarion.", priority: 5},
    { date: "Baba 24", feast: "The Martyrdom of the Sts. Paul, Longinus and Deenah (Zena).", priority: 5},
    { date: "Baba 25", feast: "The Departure of the Saints Apollo and Epip.", priority: 5},
    { date: "Baba 25", feast: "The Commemoration of the Consecration of the Church of Saint Julius El-Akfahsee (Aqfahs).", priority: 5},
    { date: "Baba 26", feast: "The Martyrdom of Saint Timon the Apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Baba 26", feast: "The Commemoration of the Seven Martyrs on the Mount of St. Antonius.", priority: 5},
    { date: "Baba 27", feast: "The Martyrdom of the Righteous Father Saint Macarius Bishop of Edkow (Tkoou)", priority: 5, type: ["Bishop","Martyr"], saintName: "St. Macarius Bishop of Edkow"},
    { date: "Baba 28", feast: "Martyrdom of the Sts. Marcian (Marcianus) and Mercurius", priority: 5},
    { date: "Baba 29", feast: "The Martyrdom of St. Demetrius of Thessalonica", priority: 5},
    { date: "Baba 30", feast: "The Commemoration of the Consecration of the Church of St. Mark the Evangelist and the Appearance of His Holy Head.", priority: 5, type: ["Apostle","Martyr"], saintName: "St. Mark The Evangelist"},
    { date: "Baba 30", feast: "The Departure of St. Ibrahim (Ibraham) the Hermit.", priority: 5},
    { date: "Hator 1", feast: "The Martyrdom of the Saints Maximus, Numitius, Victor (Boctor), and Philip (Philopus).", priority: 5, type: ["Martyr"], saintName: "St. Victor"},   
    { date: "Hator 1", feast: "The Commemoration of Saint Cleopas the Apostle and His Companion.", priority: 5, type: ["Apostle"], saintName: "Any Apostle"},
    { date: "Hator 2", feast: "The Departure of St. Peter the Third 27th Pope of Alexandria", priority: 5},
    { date: "Hator 3", feast: "The Departure of St. Cyriacus.", priority: 5},
    { date: "Hator 3", feast: "The Departure of St. Athanasius and His Sister, Irene.", priority: 5},
    { date: "Hator 4", feast: "The Martyrdom of Saints John and James, Bishops of Persia.", priority: 5},
    { date: "Hator 4", feast: "The Martyrdom of Saints Epimachus and Adrianus (Azarianus).", priority: 5},
    { date: "Hator 5", feast: "The Appearance of the Head of St. Longinus, the Soldier.", priority: 5},
    { date: "Hator 5", feast: "The Martyrdom of St. Timothy and the Relocation of the Body of St. Theodore, the Prince, to Shotb.", priority: 5, type: ["Martyr"], saintName: "St. Theodorus El-Shotbe"},           
    { date: "Hator 6", feast: "The Departure of St. Felix, Pope of Rome.", priority: 5},
    { date: "Hator 6", feast: "The Consecration of the church of the Virgin in the Mouharaque Monastery in Quosquam Mount.", priority: 5},
    { date: "Hator 7", feast: "The Martyrdom of St. George of Alexandria.", priority: 5},
    { date: "Hator 7", feast: "The Martyrdom of St. Nehroua.", priority: 5},
    { date: "Hator 7", feast: "The Departure of St. Mina, Bishop of Tamai (Thmoui).", priority: 5},
    { date: "Hator 7", feast: "The Consecration of the Church of St. George of Cappadocia.", priority: 5, type: ["Martyr"], saintName: "St. George, Prince of the Martyrs"},
    { date: "Hator 8", feast: "The Commemoration of the Four Incorporeal Creatures", priority: 5, type: ["Heavenly"], saintName: "The Four Incorporeal Creatures"},
    { date: "Hator 9", feast: "The Departure of the Holy Father Anba Isaac, 41st Pope of Alexandria.", priority: 5},
    { date: "Hator 9", feast: "The Assembly of the Ecumenical Council at Nicea.", priority: 5},
    { date: "Hator 10", feast: "The Martyrdom of St. Sophia and the Fifty Virgins with her.", priority: 5},
    { date: "Hator 10", feast: "The Assembly of a Council in Rome because of the Feast of Theophany and Lent.", priority: 5},
    { date: "Hator 11", feast: "The Departure of St. Anna (Hannah), the mother of the Theotokos.", priority: 5},
    { date: "Hator 11", feast: "The Commemoration of the Martyrdom of St. Archelaus and the Martyrdom of Elisha the Hegumen.", priority: 5},
    { date: "Hator 12", feast: "The Commemoration of the Honored Archangel Michael", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Hator 13", feast: "The Departure of St. Timothy, Bishop of Ansena (Antinoe).", priority: 5},
    { date: "Hator 13", feast: "The Departure of St. Zacharias, 64th Pope of Alexandria.", priority: 5},
    { date: "Hator 14", feast: "The Departure of St. Martinus (Martin) Bishop of Tours (Thrace)", priority: 5},
    { date: "Hator 15", feast: "The Martyrdom of Saint Mina, the Wonder Worker", priority: 5, type: ["Martyr"], saintName: "St. Mina the Wonder Worker"},
    { date: "Hator 16", feast: "The Beginning of the Fast of the Nativity (Advent) in the Coptic Church.", priority: 5},
    { date: "Hator 16", feast: "The Consecration of the Church of St. Abu-Nofer (Onuphrius).", priority: 5},
    { date: "Hator 16", feast: "The Martyrdom of Saint Yostus, the Bishop.", priority: 5},
    { date: "Hator 17", feast: "The Departure of Saint John Chrysostom", priority: 5},
    { date: "Hator 18", feast: "The Martyrdom of the Two Saints: Atrasis and Yoana (Junia).", priority: 5},
    { date: "Hator 18", feast: "The Martyrdom of Saint Philip the Apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Hator 19", feast: "The Consecration of the Church of St. Sergius and St. Bacchus.", priority: 5, type: ["Martyr"], saintName: "Sts. Sergius & Bacchus"},
    { date: "Hator 19", feast: "The Commemoration of the Preaching of St. Bartholomew, the Apostle.", priority: 5, type: ["Apostle"], saintName: "Any Apostle"},
    { date: "Hator 20", feast: "The Departure of St. Anianus, 2nd Pope of Alexandria.", priority: 5},
    { date: "Hator 20", feast: "The Consecration of the Churches of Prince Theodore, the Son of John El-Shotbe, and Prince Theodore El-Mishreke.", priority: 5, type: ["Martyr"], saintName: "St. Theodorus El-Shotbe"},
    { date: "Hator 21", feast: "The Commemoration of the Virgin St. Mary, the Theotokos.", priority: 5},
    { date: "Hator 21", feast: "The Departure of Saint Gregory, the Wonder Worker.", priority: 5},
    { date: "Hator 21", feast: "The Departure of Saint Cosma, 54th Pope of Alexandria.", priority: 5},
    { date: "Hator 21", feast: "The Commemoration of the Holy Martyrs Alphaeus, Zacchaeus, Romanus and John, and the Commemoration of the Saints Thomas, Victor, and Isaac of the City of Ashmunen.", priority: 5},
    { date: "Hator 22", feast: "The Martyrdom of Saints Cosmas, Damian, Their Brothers and Their Mother", priority: 5, type: ["Martyr"], saintName: "Sts. Cosmas & Damian"},
    { date: "Hator 23", feast: "The Departure of St. Cornelius the Centurion.", priority: 5},
    { date: "Hator 23", feast: "The Consecration of the Church of St. Marina.", priority: 5},
    { date: "Hator 24", feast: "The Commemoration of the Twenty Four Presbyters", priority: 5, type: ["Heavenly"], saintName: "The Twenty Four Presbyters"},
    { date: "Hator 25", feast: "The Martyrdom of St. Philopatir Mercorios Known as the Saint with the Two Swords", priority: 5, type: ["Martyr"], saintName: "St. Philopatir Mercorios"},   
    { date: "Hator 26", feast: "The Commemoration of the Martyrdom of the Sts. Valerian (Balaryanos) and Tiburcius (Thiborinos), His Brother.", priority: 5},
    { date: "Hator 26", feast: "The Commemoration of St. Gregory, Bishop of Nyssa.", priority: 5},
    { date: "Hator 27", feast: "The Martyrdom of St. James the Mangled (Sawn).", priority: 5},
    { date: "Hator 28", feast: "The Martyrdom of St. Sarapamon, Bishop of Niku.", priority: 5, type: ["Martyr"], saintName: "St. Sarapamon Bishop of Niku"},
    { date: "Hator 29", feast: "The Martyrdom of St. Peter, the Seal of the Martyrs, 17th Pope of Alexandria.", priority: 5},
    { date: "Hator 29", feast: "The Martyrdom of St. Clement, Pope of Rome.", priority: 5},
    { date: "Hator 30", feast: "The Departure of St. Acacius, Patriarch of Constantinople.", priority: 5},
    { date: "Hator 30", feast: "The Martyrdom of St. Macarius.", priority: 5},
    { date: "Hator 30", feast: "The Consecration of the Church of Saints Cosmas, Damian, Their Brothers and Their Mother.", priority: 5, type: ["Martyr"], saintName: "Sts. Cosmas & Damian"},
    { date: "Kiahk 1", feast: "The Departure of St. Peter Elrahawy, Bishop of Gaza.", priority: 5},
    { date: "Kiahk 1", feast: "The Consecration of the Church of the Saint Abba Shenouda.", priority: 5, type: ["Saint"], saintName: "St. Shenouda the Archimandrite"},   
    { date: "Kiahk 2", feast: "The Departure of the Saint Abba Hor, the Monk.", priority: 5},
    { date: "Kiahk 3", feast: "The Entrance of Saint Mary into the Temple at Jerusalem.", priority: 5},
    { date: "Kiahk 4", feast: "The Martyrdom of St. Andrew the Apostle, the Brother of St. Peter.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Kiahk 5", feast: "The Departure of Nahum, the Prophet.", priority: 5},
    { date: "Kiahk 5", feast: "The Martyrdom of St. Victor (Boctor).", priority: 5, type: ["Martyr"], saintName: "St. Victor"},
    { date: "Kiahk 5", feast: "The Martyrdom of St. Isidore (Isidorus).", priority: 5},
    { date: "Kiahk 6", feast: "", priority: 5},
    { date: "Kiahk 6", feast: "The Martyrdom of St. Anatolius (Anatole).", priority: 5},
    { date: "Kiahk 7", feast: "The Departure of St. Matthew the Poor.", priority: 5},
    { date: "Kiahk 8", feast: "The Departure of St. Heraclas (Theoclas), 13th Pope of Alexandria.", priority: 5},
    { date: "Kiahk 8", feast: "The Martyrdom of the Saints: Barbara and Juliana.", priority: 5, type: ["Female Martyr"], saintName: "Sts. Barbara and Juliana"},
    { date: "Kiahk 8", feast: "The Martyrdom of the Saints: Esi (Isi) and His Sister Thecla.", priority: 5},
    { date: "Kiahk 8", feast: "The Departure of St. Samuel the Abbot of El-Qualamon Monastery (Abba Samuel the Confessor).", priority: 5, type: ["Saint"], saintName: "St. Samuel the Confessor"},  
    { date: "Kiahk 8", feast: "The departure of St. Yustus, the monk of St. Anthony's monastery.", priority: 5},
    { date: "Kiahk 9", feast: "The Departure of St. Poemin, the Confessor.", priority: 5},
    { date: "Kiahk 10", feast: "The Relocation of the Body of St. Severus, Patriarch of Antioch.", priority: 5, type: ["Patriarch", "Saint"], saintName: "St. Severus of Antioch"},  
    { date: "Kiahk 10", feast: "The Departure of St. Nicholas, the Confessor, Bishop of Myra (Mora).", priority: 5},
    { date: "Kiahk 11", feast: "The Departure of the Saint Abba Pijimi.", priority: 5},
    { date: "Kiahk 12", feast: "The Commemoration of the Honorable Michael, the Archangel.", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Kiahk 12", feast: "The Departure of St. Hedra, Bishop of Aswan.", priority: 5},
    { date: "Kiahk 12", feast: "The Commemoration of St. John the Confessor.", priority: 5},
    { date: "Kiahk 12", feast: "Assembly of a Council in Rome Against Benates (Novatus) the Priest.", priority: 5},
    { date: "Kiahk 13", feast: "The Martyrdom of St. Barsanuphius.", priority: 5},
    { date: "Kiahk 13", feast: "The Departure of St. Abracius (Apraxios).", priority: 5},
    { date: "Kiahk 13", feast: "The Consecration of the Church of St. Misaeal (Misayil), the Anchorite.", priority: 5},
    { date: "Kiahk 14", feast: "The Martyrdom of Saints Behnam and Sarah, His Sister.", priority: 5},
    { date: "Kiahk 14", feast: "The Departure of Saint Christodoulos.", priority: 5},
    { date: "Kiahk 14", feast: "The Martyrdom of Saints Simeon of Menouf, Abba Hor, and Abba Mina the Elder.", priority: 5},
    { date: "Kiahk 14", feast: "The Martyrdom of Saint Ammonius, Bishop of Esna (Latopolis).", priority: 5},
    { date: "Kiahk 15", feast: "The Departure of St. Gregory, Patriarch of the Armenians.", priority: 5},
    { date: "Kiahk 16", feast: "The Departure of the Righteous Gideon, One of the Judges of Israel.", priority: 5},
    { date: "Kiahk 16", feast: "The Martyrdom of Saints Harouadi, Ananias and Khouzi.", priority: 5},
    { date: "Kiahk 16", feast: "The Consecration of the Church of St. James, the Persian.", priority: 5},
    { date: "Kiahk 17", feast: "The Commemoration of the Departure of St. Luke the Stylite and the Relocation of His Holy Relics.", priority: 5},        
    { date: "Kiahk 18", feast: "The Commemoration of the Relocation of the Relics of St. Titus to Constantinople.", priority: 5},
    { date: "Kiahk 18", feast: "The Commemoration of St. Heracleas the Martyr and St. Philemon the Priest.", priority: 5},
    { date: "Kiahk 19", feast: "The Departure of St. John, Bishop of El-Borollos Who Gathered the Biographies of the Saints (The Synaxarion).", priority: 5},
    { date: "Kiahk 20", feast: "The Departure of the Upright Haggai the Prophet.", priority: 5},
    { date: "Kiahk 21", feast: "The Commemoration of the Virgin Mary, the Theotokos.", priority: 5},
    { date: "Kiahk 21", feast: "The Martyrdom of St. Barnabas, One of the Seventy Apostles.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Kiahk 22", feast: "The Commemoration of the Archangel Gabriel.", priority: 5, type: ["Heavenly"], saintName: "Archangel Gabriel"},
    { date: "Kiahk 22", feast: "The Departure of St. Anastasius, 36th Pope of Alexandria.", priority: 5},
    { date: "Kiahk 23", feast: "The Departure of David, the Prophet and King.", priority: 5},
    { date: "Kiahk 23", feast: "The Departure of St. Timothy, the Anchorite.", priority: 5},
    { date: "Kiahk 24", feast: "The Martyrdom of St. Ignatius, Patriarch of Antioch.", priority: 5},
    { date: "Kiahk 24", feast: "The Departure of St. Philogonus, Patriarch of Antioch.", priority: 5},
    { date: "Kiahk 24", feast: "The Birth of St. Takla Haymanot, the Ethiopian.", priority: 5, type: ["Saint"], saintName: "St. Takla Haymanot"},   
    { date: "Kiahk 25", feast: "The Departure of St. John Kama (Khame).", priority: 5, type: ["Saint"], saintName: "St. John Kama"},    
    { date: "Kiahk 26", feast: "The Martyrdom of St. Anastasia.", priority: 5},
    { date: "Kiahk 26", feast: "The Commemoration of St. Juliana the Martyr.", priority: 5},
    { date: "Kiahk 27", feast: "The Martyrdom of St. Anba 'Bisadi' (Psote), the Bishop.", priority: 5},
    { date: "Kiahk 28", feast: "The Martyrdom of 150 Men and 24 Women from Ansena.", priority: 5},
    { date: "Kiahk 29", feast: "The Feast of the Nativity of Our Lord Jesus Christ (Christmas).", priority: 5},
    { date: "Kiahk 30", feast: "The Departure of St. John, Archpriest of Scetis.", priority: 5},
    { date: "Tobe 1", feast: "The Martyrdom of St. Stephen the Archdeacon.", priority: 5, type: ["Martyr"], saintName: "St. Stephen The Archdeacon"},
    { date: "Tobe 1", feast: "The Martyrdom of St. Lawindianus (Leontius).", priority: 5},
    { date: "Tobe 2", feast: "The Departure of St. Theonas, 16th Pope of Alexandria.", priority: 5},
    { date: "Tobe 2", feast: "The Martyrdom of St. Callinicus (Gallinicus), Bishop of Oseem.", priority: 5},
    { date: "Tobe 3", feast: "The Commemoration of the Slain Children of Bethlehem by the Order of King Herod", priority: 5},
    { date: "Tobe 4", feast: "The Departure of St. John the Evangelist and Theologian", priority: 5, type: ["Apostle","Saint"], saintName: "St. John The Evangelist"},
    { date: "Tobe 5", feast: "Martyrdom of St.Eusegnius (Eugenius) the Soldier", priority: 5},
    { date: "Tobe 6", feast: "The Commemoration of the Circumcision of the Lord Christ.", priority: 5},
    { date: "Tobe 6", feast: "The Ascension of Elijah the Prophet.", priority: 5},
    { date: "Tobe 6", feast: "The Departure of St. Marcianus, 8th Pope of Alexandria.", priority: 5},
    { date: "Tobe 6", feast: "The Departure of St. Basil the Great, Bishop Of Caesarea.", priority: 5},
    { date: "Tobe 7", feast: "The Departure of St. Sylvester, Pope of Rome", priority: 5},
    { date: "Tobe 8", feast: "Consecration of The Church of Saint Macarius the Great", priority: 5, type: ["Saint"], saintName: "St. Macarius The Great"},  
    { date: "Tobe 8", feast: "Departure of Pope Andronicus I", priority: 5},
    { date: "Tobe 8", feast: "Departure of Pope Benjamin I", priority: 5},
    { date: "Tobe 9", feast: "The Departure of Abba Abraam, Companion of Abba Gawarga.", priority: 5},
    { date: "Tobe 10", feast: "Paramouni of Holy Theophany (Epiphany).", priority: 5},
    { date: "Tobe 11", feast: "The Holy Theophany of Our Lord, God and Savior, Jesus Christ (Baptism of the Lord christ).", priority: 5},
    { date: "Tobe 12", feast: "The Commemoration of the Archangel Michael.", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Tobe 12", feast: "The Martyrdom of St. Theodore El-Mashriqi (the Oriental).", priority: 5, type: ["Martyr"], saintName: "St. Theodore El-Mashriqi"},
    { date: "Tobe 12", feast: "The Martyrdom of St. Anatole (Anatolius).", priority: 5},
    { date: "Tobe 13", feast: "The Commemoration of the Miracle at Cana of Galilee.", priority: 5},
    { date: "Tobe 13", feast: "The Departure of St. Theophilus, the Monk.", priority: 5},
    { date: "Tobe 13", feast: "The Martyrdom of St. Demiana.", priority: 5, type: ["Female Martyr"], saintName: "St. Demiana"},
    { date: "Tobe 14", feast: "The Departure of St. Archiledis (Arselidas).", priority: 5},
    { date: "Tobe 14", feast: "The Departure of St. Maximus, Brother of St. Domadius (Domatius).", priority: 5, type: ["Saint"], saintName: "St. Maximus and St. Domatius"},     
    { date: "Tobe 15", feast: "The Departure of Obadiah, the Prophet.", priority: 5},
    { date: "Tobe 16", feast: "The Martyrdom of St. Philotheus.", priority: 5},
    { date: "Tobe 16", feast: "The Departure of St. John IV, 48th Pope of Alexandria.", priority: 5},
    { date: "Tobe 17", feast: "The Departure of St. Maximus and St. Domatius (Domadius).", priority: 5, type: ["Saint"], saintName: "St. Maximus and St. Domatius"},    
    { date: "Tobe 17", feast: "The Departure of Anba Yusab, Bishop of Girga, known as El- Abbah.", priority: 5},
    { date: "Tobe 18", feast: "The Departure of St. James, Bishop of Nisibis.", priority: 5},
    { date: "Tobe 19", feast: "The Discovery of the Relics of St. Abahor (Pihour) St. Bisoura (Pisoura) and their Mother Ampira (Asra).", priority: 5},  
    { date: "Tobe 20", feast: "The Departure of St. Prochorus, One of the Seventy Disciples.", priority: 5},
    { date: "Tobe 20", feast: "The Commemoration of the Consecration of the Church of St. John, the Owner of the Golden Gospel, and the Transfer of His Relics to It. Also, the Commemoration of the Martyrdom of Anba Behna (Bahnou) and Anba Kloag (Bagoug), the Priest.", priority: 5},
    { date: "Tobe 21", feast: "The Dormition of Our Lady, the Virgin Mary, the Theotokos.", priority: 5},
    { date: "Tobe 21", feast: "The Departure of St. Hilaria, Daughter of Emperor Zeno.", priority: 5},
    { date: "Tobe 21", feast: "The Departure of St. Gregorius (Gregory of Nyssa), Brother of St. Basil the Great.", priority: 5},
    { date: "Tobe 22", feast: "The Departure of St. Anthony the Great (Antonius).", priority: 5, type: ["Saint"], saintName: "St. Anthony The Great"},
    { date: "Tobe 23", feast: "The Martyrdom of St. Timothy, the Apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Tobe 23", feast: "The Departure of Pope Cyril IV (Kyrillos), 110th Pope of Alexandria.", priority: 5},
    { date: "Tobe 24", feast: "The Departure of St. Mary the Ascetic (The Shut-In).", priority: 5},
    { date: "Tobe 24", feast: "The Martyrdom of Anba Bisada (St. Psati), the Priest.", priority: 5},
    { date: "Tobe 25", feast: "The Departure of St. Peter, the Worshipper.", priority: 5},
    { date: "Tobe 25", feast: "The Martyrdom of St. Askala (Asela), the Ascetic.", priority: 5},
    { date: "Tobe 26", feast: "The Martyrdom of the Forty-Nine Saints, the Elders of Sheheat (Scetis).", priority: 5},
    { date: "Tobe 26", feast: "The Departure of St. Anastasia.", priority: 5},
    { date: "Tobe 27", feast: "The Martyrdom of St. Sarapion.", priority: 5},
    { date: "Tobe 27", feast: "The Commemoration of the Archangel Suriel.", priority: 5, type: ["Heavenly"], saintName: "Archangel Suriel"},
    { date: "Tobe 27", feast: "The Relocation of the Relics of St. Timothy, the Apostle.", priority: 5, type: ["Apostle", "Martyr"], saintName: "Any Apostle"},
    { date: "Tobe 27", feast: "The Martyrdom of St. Abe-Fam, the Soldier (St. Phoebammon).", priority: 5},
    { date: "Tobe 28", feast: "The Martyrdom of St. Clement.", priority: 5},
    { date: "Tobe 28", feast: "The Martyrdom of St. Anba Kaou.", priority: 5},
    { date: "Tobe 29", feast: "The Departure of St. Eksani (St. Xene).", priority: 5},
    { date: "Tobe 29", feast: "The Commemoration of St. Seriakos (Syriacus), the Fighter.", priority: 5},
    { date: "Tobe 30", feast: "The Martyrdom of Saints Pistis, Helpis, Agape, and Their Mother, Sophia.", priority: 5},
    { date: "Meshir 1", feast: "The Commemoration of the Ecumenical Council in Constantinople.", priority: 5},
    { date: "Meshir 1", feast: "The Commemoration of the Consecration of the Church of St. Peter, the Seal of Martyrs.", priority: 5},
    { date: "Meshir 2", feast: "The Departure of the Great Saint Anba Paul, the First Hermit.", priority: 5, type: ["Saint"], saintName: "St. Paul The First Hermit"},
    { date: "Meshir 2", feast: "The Departure of St. Longinus, Abbot of El-Zugag Monastery.", priority: 5},
    { date: "Meshir 3", feast: "The Departure of St. James, the Ascetic.", priority: 5},
    { date: "Meshir 4", feast: "The Martyrdom of St. Agabus, One of the Seventy Disciples.", priority: 5},
    { date: "Meshir 5", feast: "The Departure of St. Agrippinus, 10th Pope of Alexandria.", priority: 5},
    { date: "Meshir 5", feast: "The Commemoration of the Saints Anba Bishay and Anba Abanoub.", priority: 5},
    { date: "Meshir 5", feast: "The Departure of St. Apollo, friend of Anba Epip.", priority: 5},
    { date: "Meshir 5", feast: "The Commemoration of the Relocation of the Relics of the Forty-Nine Elders of the Wilderness of Shiheet (Scetis).", priority: 5},
    { date: "Meshir 6", feast: "The Appearance of the Body of St. Apolidus (Hippolytus), Pope of Rome.", priority: 5},
    { date: "Meshir 6", feast: "The Martyrdom of the Saints Abakir, John, the Three Virgins and Their Mother.", priority: 5, type: ["Martyr"], saintName: "Sts. Abakir and John"},
    { date: "Meshir 7", feast: "The Martyrdom of St. Fabianus (Fabrianus), Pope of Rome.", priority: 5},
    { date: "Meshir 8", feast: "The Feast of Presenting the Lord Christ in the Temple.", priority: 5},
    { date: "Meshir 9", feast: "The Departure of St. Severus, Patriarch of Antioch.", priority: 5, type: ["Patriarch", "Saint"], saintName: "St. Severus of Antioch"},  
    { date: "Meshir 9", feast: "The Departure of St. James (Yacobus), 50th Pope of Alexandria.", priority: 5},
    { date: "Meshir 10", feast: "The Martyrdom of St. James the Apostle, Son of Alphaeus.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Meshir 10", feast: "The Martyrdom of St. Justus, Son of Emperor Numerian.", priority: 5},
    { date: "Meshir 10", feast: "The Departure of St. Isidore of Pelusium.", priority: 5},
    { date: "Meshir 10", feast: "The Martyrdom of St. Philo, Bishop of the Persian.", priority: 5},
    { date: "Meshir 11", feast: "The Martyrdom of St. Fabianus (Fabrianus), Pope of Rome.", priority: 5},
    { date: "Meshir 12", feast: "The Commemoration of the Archangel Michael.", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Meshir 12", feast: "The Departure of St. Gelasius.", priority: 5},
    { date: "Meshir 13", feast: "The Martyrdom of St. Sergius of Atripe, His Father, Mother, Sister, and Many Others with Them.", priority: 5},
    { date: "Meshir 13", feast: "The Departure of St. Timothy III, 32nd Pope of Alexandria.", priority: 5},
    { date: "Meshir 14", feast: "The Departure of St. Severus, Patriarch of Antioch.", priority: 5, type: ["Patriarch", "Saint"], saintName: "St. Severus of Antioch"}, 
    { date: "Meshir 14", feast: "The Departure of St. James (Yacobus), 50th Pope of Alexandria.", priority: 5},
    { date: "Meshir 15", feast: "The Departure of St. Zechariah, the Prophet.", priority: 5},
    { date: "Meshir 15", feast: "The Consecration of the First Church Dedicated for the Forty Martyrs of Sebaste.", priority: 5},
    { date: "Meshir 15", feast: "The Departure of St. Paphnoute (Paphnotius).", priority: 5},
    { date: "Meshir 16", feast: "Departure of St. Elizabeth", priority: 5},
    { date: "Meshir 17", feast: "The Martyrdom of St. Mina (Menas), the Monk.", priority: 5},
    { date: "Meshir 18", feast: "The Departure of St. Malatius the Confessor, Patriarch of Antioch.", priority: 5},
    { date: "Meshir 19", feast: "The Commemoration of the Relocation of the Relics of St. Martianus, the Monk.", priority: 5},
    { date: "Meshir 20", feast: "The Departure of St. Peter, 21st Pope of Alexandria.", priority: 5},
    { date: "Meshir 20", feast: "The Commemoration of Sts. Basil, Theodore and Timothy, the Martyrs.", priority: 5},
    { date: "Meshir 21", feast: "The Commemoration of the Virgin St. Mary.", priority: 5},
    { date: "Meshir 21", feast: "The Martyrdom of St. Onesimus, the Disciple of St. Paul.", priority: 5},
    { date: "Meshir 21", feast: "The Departure of St. Gabriel, 57th Pope of Alexandria.", priority: 5},
    { date: "Meshir 21", feast: "The Departure of St. Zacharias, Bishop of Sakha.", priority: 5},
    { date: "Meshir 22", feast: "The Departure of St. Maruta (Maruthas) the Bishop.", priority: 5},
    { date: "Meshir 23", feast: "The Martyrdom of St. Eusebius, Son of Basilides, the Minister.", priority: 5},
    { date: "Meshir 24", feast: "The Departure of St. Agapetus (Agapius), the Bishop.", priority: 5},
    { date: "Meshir 24", feast: "The Martyrdom of St. Timothy and St. Matthias.", priority: 5},
    { date: "Meshir 25", feast: "The Martyrdom of Sts. Archippus, Philemon and Lycia the Virgin.", priority: 5},
    { date: "Meshir 25", feast: "The Martyrdom of St. Quona (Kona) and St. Mina.", priority: 5},
    { date: "Meshir 26", feast: "The Departure of St. Hosea, the Prophet.", priority: 5},
    { date: "Meshir 26", feast: "The Martyrdom of St. Zadok and the 128 who were with Him.", priority: 5},
    { date: "Meshir 27", feast: "The Departure of St. Eustathius, Patriarch of Antioch.", priority: 5},
    { date: "Meshir 28", feast: "The Martyrdom of St. Theodore, the Roman.", priority: 5},
    { date: "Meshir 29", feast: "The Martyrdom of St. Polycarp, Bishop of Smyrna.", priority: 5},
    { date: "Meshir 30", feast: "The Appearance of the Head of St. John the Baptist.", priority: 5, type: ["Heavenly"], saintName: "St. John the Baptist"},
    { date: "Meshir 30", feast: "Abba Kyrillos the Sixth, the 116th Pope of Alexandria.", priority: 5, type: ["Pope"], saintName: "Pope Kyrillos VI"},
    { date: "Paremhotep 1", feast: "The Departure of St. Narcissus.", priority: 5},
    { date: "Paremhotep 1", feast: "The Martyrdom of St. Alexandrus.", priority: 5},
    { date: "Paremhotep 1", feast: "Commemoration of Anba Marcura.", priority: 5},
    { date: "Paremhotep 2", feast: "The Martyrdom of St. Macrobius (Makrawy) the Bishop.", priority: 5},
    { date: "Paremhotep 3", feast: "The Departure of St. Cosmas, the Fifty-Eighth Pope of Alexandria.", priority: 5},
    { date: "Paremhotep 3", feast: "The Martyrdom of St. Porphyry.", priority: 5},
    { date: "Paremhotep 3", feast: "The Departure of St. Hadid the priest.", priority: 5},
    { date: "Paremhotep 4", feast: "Assembly of the Holy Council on the island of Bani-Omar.", priority: 5},
    { date: "Paremhotep 4", feast: "The Martyrdom of St. Haboulyous (Hanulius) the prince.", priority: 5},
    { date: "Paremhotep 5", feast: "The Departure of Anba Serapamon, Archpriest of Abba Yehnis (John) monastery.", priority: 5},
    { date: "Paremhotep 5", feast: "Commemoration of the Martyrdom of St. Eudexia (Eutychia).", priority: 5},
    { date: "Paremhotep 5", feast: "The Martyrdom of St. Peter the priest.", priority: 5},
    { date: "Paremhotep 6", feast: "The Martyrdom of St. Dioscorus.", priority: 5},
    { date: "Paremhotep 6", feast: "The Departure of St. Theodotus, the bishop.", priority: 5},
    { date: "Paremhotep 7", feast: "The Martyrdom of Sts. Philemon and Apollonius.", priority: 5},
    { date: "Paremhotep 7", feast: "The Martyrdom of St. Mary the Israelite.", priority: 5},
    { date: "Paremhotep 8", feast: "The Martyrdom of St. Matthias, the apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Paremhotep 8", feast: "The Departure of St. Julian, the Eleventh Pope of Alexandria.", priority: 5},
    { date: "Paremhotep 8", feast: "The Martyrdom of St. Arianus, the Governor of Ansena.", priority: 5},
    { date: "Paremhotep 9", feast: "The Departure of St. Konan.", priority: 5},
    { date: "Paremhotep 9", feast: "The Martyrdom of Sts. Abrianus, Amrata his wife, Eusebius, Armanius, and the Forty Martyrs.", priority: 5},
    { date: "Paremhotep 10", feast: "Commemoration Of the Appearance Of The Glorious Cross.", priority: 5},
    { date: "Paremhotep 11", feast: "The Martyrdom Of St. Basil (Basilaos) The Bishop.", priority: 5},
    { date: "Paremhotep 12", feast: "The Commemoration of the Honorable Angel Michael.", priority: 5},
    { date: "Paremhotep 12", feast: "The Commemoration of the revealing of the virginity of St. Demetrius the Twelfth Pope of Alexandria.", priority: 5},
    { date: "Paremhotep 12", feast: "The Martyrdom of St. Malachias of Palestine.", priority: 5},
    { date: "Paremhotep 12", feast: "The Martyrdom of St. Glathinos in Damascus.", priority: 5},
    { date: "Paremhotep 13", feast: "The Departure of Abba Dionysius, the Fourteenth Pope of Alexandria.", priority: 5},
    { date: "Paremhotep 13", feast: "The Return of the Great Sts. Anba Macarius the Great and Anba Macarius of Alexandria, from Exile.", priority: 5, type: ["Saint"], saintName: "St. Macarius The Great"},    
    { date: "Paremhotep 13", feast: "The Return of the Great Sts. Anba Macarius the Great and Anba Macarius of Alexandria, from Exile.", priority: 5, type: ["Saint"], saintName: "St. Macarius The Alexandrian"},       
    { date: "Paremhotep 13", feast: "The Martyrdom of the Forty Martyrs of Sebastia.", priority: 5},
    { date: "Paremhotep 14", feast: "The Departure of Anba Kyrellos (Cyril) the Seventy Fifth Pope of Alexandria.", priority: 5},
    { date: "Paremhotep 14", feast: "The Martyrdom of St. Shenouda (Sinouti) El Bahnasawy.", priority: 5},
    { date: "Paremhotep 14", feast: "The Martyrdom of the Sts. Eugenius, Agathodorus and Elpidius.", priority: 5},
    { date: "Paremhotep 15", feast: "The Departure of St. Sarah the nun.", priority: 5},
    { date: "Paremhotep 15", feast: "The Martyrdom of St. Helias of Hnes.", priority: 5},
    { date: "Paremhotep 16", feast: "The Departure Of The Saint Anba Khail (Mikhail) The Forty Six Pope Of The See Of St. Mark.", priority: 5},
    { date: "Paremhotep 17", feast: "The Departure of Lazarus, the beloved of the Lord.", priority: 5},
    { date: "Paremhotep 17", feast: "The Commemoration of the Sts. George the ascetic, Belasius the martyr, and Anba Joseph the bishop.", priority: 5},  
    { date: "Paremhotep 17", feast: "The Departure of St. Basilius, Bishop of Jerusalem.", priority: 5},
    { date: "Paremhotep 17", feast: "The Martyrdom of St. Sedhom Bishay in Domiat.", priority: 5},
    { date: "Paremhotep 18", feast: "The Martyrdom of St. Isidore, Friend of Sina the Soldier.", priority: 5},
    { date: "Paremhotep 19", feast: "The Martyrdom of St. Aristobulus, the apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Paremhotep 19", feast: "The Martyrdom of the Sts. Alexander, Agabius, Alexander, Timol (Timolaos), Dionysius, Romulus, and Blesius (Valesius).", priority: 5},
    { date: "Paremhotep 20", feast: "The Departure Of the St. Anba Khail (Mikhail) the Fifty Six Pope of the See of St. Mark.", priority: 5},
    { date: "Paremhotep 20", feast: "Raising of Lazarus from the dead.", priority: 5},
    { date: "Paremhotep 21", feast: "Commemoration of the Theotokos and Ever-Virgin St. Mary", priority: 5},
    { date: "Paremhotep 21", feast: "Commemoration of the visit of Our Lord Christ to Bethany", priority: 5},
    { date: "Paremhotep 21", feast: "Consultation of the Chief Priests to put the righteous Lazarus to death", priority: 5},
    { date: "Paremhotep 22", feast: "The Departure of St. Kyrellos (Cyril), Bishop of Jerusalem.", priority: 5},
    { date: "Paremhotep 22", feast: "The Departure of St. Michael, Bishop of Naqadah.", priority: 5},
    { date: "Paremhotep 23", feast: "The Departure of the Great Prophet Daniel.", priority: 5},
    { date: "Paremhotep 24", feast: "The Apparition of the Pure Lady the Virgin in the church of Zeiton.", priority: 5},
    { date: "Paremhotep 24", feast: "The Departure of Anba Macarius, the Fifty-Ninth Pope of Alexandria.", priority: 5},
    { date: "Paremhotep 25", feast: "The Commemoration of the Crucifixion of Our Lord Jesus Christ.", priority: 5},
    { date: "Paremhotep 25", feast: "The Departure of St. Macarius the Great.", priority: 5, type: ["Saint"], saintName: "St. Macarius The Great"}, 
    { date: "Paremhotep 25", feast: "The Martyrdom of St. Domicos.", priority: 5},
    { date: "Paremhotep 26", feast: "The Departure of St. Euphrasia (Eupraxia), the virgin.", priority: 5},
    { date: "Paremhotep 26", feast: "The Departure of Pope Peter VI, the One Hundred and Fourth Pope of Alexandria.", priority: 5},
    { date: "Paremhotep 27", feast: "The Commemoration of the Crucifixion of Our Lord Jesus Christ.", priority: 5},
    { date: "Paremhotep 27", feast: "The Departure of St. Macarius the Great.", priority: 5, type: ["Saint"], saintName: "St. Macarius The Great"}, 
    { date: "Paremhotep 27", feast: "The Martyrdom of St. Domicos.", priority: 5},
    { date: "Paremhotep 28", feast: "The Departure of the righteous Emperor Constantine the Great.", priority: 5},
    { date: "Paremhotep 28", feast: "The Departure of Pope Peter (Petros) VII, the One Hundred and Ninth Patriarch.", priority: 5},
    { date: "Paremhotep 28", feast: "The commemoration of Anba Sarapamon, known as 'The Veiled' Bishop of El-Monofia.", priority: 5},
    { date: "Paremhotep 29", feast: "The Commemoration of the Life giving Annunciation.", priority: 5},
    { date: "Paremhotep 29", feast: "The Commemoration of the Resurrection of the Lord Christ from the dead.", priority: 5},
    { date: "Paremhotep 30", feast: "The Commemoration of the Archangel Gabriel the Announcer.", priority: 5, type: ["Heavenly"], saintName: "Archangel Gabriel"},
    { date: "Paremhotep 30", feast: "The Commemoration of the Transfer of the Relies of St. James, known as the Mangled.", priority: 5},
    { date: "Paremhotep 30", feast: "The Commemoration of Samson, One of the Judges of Israel.", priority: 5},
    { date: "Parmoute 1", feast: "The Martyrdom of the Holy Virgins: Agape, Eirene, and Shiona.", priority: 5},
    { date: "Parmoute 1", feast: "The Martyrdom of the One Hundred and Fifty believers by the hand of king of Persia.", priority: 5},
    { date: "Parmoute 2", feast: "The Martyrdom of St. James the Apostle Brother of St. John the Apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Parmoute 3", feast: "The Departure of St. John, Bishop of Jerusalem.", priority: 5},
    { date: "Parmoute 3", feast: "The Departure of the holy father Anba Michael, the Seventy First Pope of the See of St. Mark.", priority: 5},
    { date: "Parmoute 4", feast: "The Departure of Anba Isaac, the Disciple of Anba Apollo.", priority: 5},
    { date: "Parmoute 4", feast: "The Departure of Pope Gabriel II, the Seventy Pope of Alexandria, who was known as Ibn Turaik.", priority: 5},
    { date: "Parmoute 5", feast: "The Commemoration of the Great Prophet Ezekiel, the son of Buzi.", priority: 5},
    { date: "Parmoute 5", feast: "The Martyrdom of St. Hepatius, Bishop of Gangra.", priority: 5},
    { date: "Parmoute 6", feast: "The Commemoration of the Appearance of the Lord to Thomas the Apostle after His Resurrection.", priority: 5, type: ["Apostle", "Martyr"], saintName: "St. Thomas the Apostle"},
    { date: "Parmoute 6", feast: "The Departure of St. Mary of Egypt.", priority: 5},
    { date: "Parmoute 7", feast: "The Departure of the Righteous Joachim, The Lord Christ Grandfather.", priority: 5},
    { date: "Parmoute 7", feast: "The Departure of St. Macrobius.", priority: 5},
    { date: "Parmoute 7", feast: "The Departure of Sts. Agapius, Theodora, and Metruf.", priority: 5},
    { date: "Parmoute 8", feast: "The Martyrdom of the Holy Virgins: Agape, Eirene, and Shiona.", priority: 5},
    { date: "Parmoute 8", feast: "The Martyrdom of the One Hundred and Fifty believers by the hand of king of Persia.", priority: 5},
    { date: "Parmoute 9", feast: "The Departure of St. Zosimus (Zocima).", priority: 5},
    { date: "Parmoute 9", feast: "The commemoration of the Wonder that took place on the hand of Pope Sinuthius (Shenouda I) the Fifty Fifth Patriarch.", priority: 5},
    { date: "Parmoute 10", feast: "The Departure of Anba Isaac, the Disciple of Anba Apollo.", priority: 5},
    { date: "Parmoute 10", feast: "The Departure of Pope Gabriel II, the Seventy Pope of Alexandria, who was known as Ibn Turaik.", priority: 5},        
    { date: "Parmoute 11", feast: "The Departure of st. Theodora.", priority: 5},
    { date: "Parmoute 11", feast: "The Departure of St. John, Bishop of Gaza.", priority: 5},
    { date: "Parmoute 12", feast: "The Departure of St. Alexander, Bishop of Jerusalem.", priority: 5},
    { date: "Parmoute 12", feast: "The Commemoration of St. Antonios, Bishop of Tamoui.", priority: 5},
    { date: "Parmoute 13", feast: "The Martyrdom of the Sts. Joshua and Joseph.", priority: 5},
    { date: "Parmoute 13", feast: "The Commemoration of Dionisa (Denisa) the Deaconess and Medius the Martyr.", priority: 5},
    { date: "Parmoute 13", feast: "The Departure of Pope Yoannis the Seventeenth, the 105th. Patriarch of Alexandria.", priority: 5},
    { date: "Parmoute 14", feast: "The Departure of the Holy Father Anba Maximus The Fifteenth Pope of Alexandria.", priority: 5},
    { date: "Parmoute 15", feast: "The Commemoration of the Consecration of the first altar for St. Nicholas, Bishop of Mora for the Jacobite Christians.", priority: 5},
    { date: "Parmoute 15", feast: "The Commemoration of the Consecration of the church of St. Agabus, the Apostle.", priority: 5, type: ["Apostle", "Martyr"], saintName: "Any Apostle"},
    { date: "Parmoute 15", feast: "The Departure of St. Alexandra, the Empress.", priority: 5},
    { date: "Parmoute 15", feast: "The Departure of Pope Mark (Marcus) VI, the 101st. Patriarch.", priority: 5},
    { date: "Parmoute 16", feast: "The Martyrdom of St. Antipas, Bishop of Pergamos.", priority: 5},
    { date: "Parmoute 17", feast: "The Martyrdom of St. James the Apostle Brother of St. John the Apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Parmoute 18", feast: "The Martyrdom of St. Arsenius, Slave of St. Sousnyous.", priority: 5},
    { date: "Parmoute 19", feast: "The Martyrdom of St. Simeon the Armenian, Bishop of the country of Persia and 150 with him.", priority: 5},
    { date: "Parmoute 19", feast: "The Martyrdom of the blessed Youhanna (John) Abu Nagaah El-Kabeer.", priority: 5},
    { date: "Parmoute 19", feast: "The Martyrdom of the Vizier Abu Elaala Fahd ibn Ibrahim and his companions.", priority: 5},
    { date: "Parmoute 19", feast: "The Martyrdom of Daoud (David), the Monk.", priority: 5},
    { date: "Parmoute 20", feast: "The Martyrdom of St. Babnuda (Paphnute).", priority: 5},
    { date: "Parmoute 21", feast: "The Commemoration of the Lady the Theotokos.", priority: 5},
    { date: "Parmoute 21", feast: "The Departure of St. Hierotheos, of Athens.", priority: 5},
    { date: "Parmoute 22", feast: "The Departure of St. Isaac (Ishaq), of Hourin.", priority: 5},
    { date: "Parmoute 22", feast: "The Departure of St. Alexander I, 19th Pope of the See of St. Mark.", priority: 5},
    { date: "Parmoute 22", feast: "The Departure of St. Mark 11, 49th Pope of the See of St. Mark.", priority: 5},
    { date: "Parmoute 22", feast: "The Departure of St. Michael 11, 53rd Pope of the See of St. Mark.", priority: 5},
    { date: "Parmoute 23", feast: "The Martyrdom of St. George, Prince of the Martyrs.", priority: 5, type: ["Martyr"], saintName: "St. George, Prince of the Martyrs"},
    { date: "Parmoute 24", feast: "The Departure of Pope Sinuthius (Shenouda I), 55th Pope of Alexandria.", priority: 5},
    { date: "Parmoute 24", feast: "The Martyrdom of St. Sina, the Soldier.", priority: 5},
    { date: "Parmoute 25", feast: "The Martyrdom of St. Sarah, and her two sons.", priority: 5},
    { date: "Parmoute 25", feast: "The Commemoration of Sts. Babnuda (Paphnute) the hermit, Theodore the worshipper, and the One hundred martyrs.", priority: 5},
    { date: "Parmoute 26", feast: "The Martyrdom of St. Sousenyos.", priority: 5},
    { date: "Parmoute 26", feast: "The Departure of Pope Youannis VII, 78th. Patriarch.", priority: 5},
    { date: "Parmoute 27", feast: "Martyrdom of St. Boctor Ebn Romanus", priority: 5},
    { date: "Parmoute 28", feast: "The Departure of St. Helena, The Empress.", priority: 5},
    { date: "Parmoute 28", feast: "The Departure of Pope Yoannis the Eleventh, the 89th. Patriarch of Alexandra.", priority: 5},
    { date: "Parmoute 28", feast: "The Departure of St. Gabriel the Eighth, the 97th. Patriarch of Alexandria.", priority: 5},
    { date: "Parmoute 29", feast: "The Departure of St. Erastus, the Apostle.", priority: 5, type: ["Apostle", "Saint"], saintName: "Any Apostle"},
    { date: "Parmoute 29", feast: "The Departure of St. Acacius, Bishop of Jerusalem.", priority: 5},
    { date: "Parmoute 30", feast: "The Martyrdom of the Great Saint Mark, the Apostle The Evangelist of the Land of Egypt.", priority: 5, type: ["Apostle", "Martyr"], saintName: "St. Mark the Evangelist"},
    { date: "Paona 1", feast: "The Consecration of the church of St. Leontius of Tripoli.", priority: 5},
    { date: "Paona 1", feast: "The Martyrdom of St. Qozman El-Tahawy and his companions.", priority: 5},
    { date: "Paona 1", feast: "The Consecration of the church of St. Abe-Fam (Epipham) the soldier.", priority: 5},
    { date: "Paona 2", feast: "The Commemoration of the Appearance of the Bodies of St. John the Baptist and Elisha the Prophet.", priority: 5, type: ["Heavenly", "Prophet"], saintName: "St. John the Baptist"},
    { date: "Paona 2", feast: "The Departure of Pope Yoannis the Eighteenth, the 107th. Pope of Alexandria.", priority: 5},
    { date: "Paona 3", feast: "The Construction of the first church of St. George in the cities of Birma and Beer Maa (Water Well) in the Oases.", priority: 5, type: ["Martyr"], saintName: "St. George, Prince of the Martyrs"},
    { date: "Paona 3", feast: "The Departure of St. Martha of Egypt.", priority: 5},
    { date: "Paona 3", feast: "The Martyrdom of St. Alladius the Bishop.", priority: 5},
    { date: "Paona 3", feast: "The Departure of Pope Cosmas, the 44th Patriarch.", priority: 5},
    { date: "Paona 3", feast: "The Departure of St. Abraam, bishop of El-Fayyoum.", priority: 5, type: ["Saint"], saintName: "St. Abraam Bishop of Fayyoum"},       
    { date: "Paona 4", feast: "The Martyrdom of St. Shenousi (Sanusi).", priority: 5},
    { date: "Paona 4", feast: "The Martyrdom of Saint Anba Amoun and the Righteous Sophia.", priority: 5},
    { date: "Paona 4", feast: "The Martyrdom of John of Herakleia.", priority: 5},
    { date: "Paona 4", feast: "The Departure of St. Aba-Hour.", priority: 5},
    { date: "Paona 4", feast: "The Departure of Pope Yoannis the Eighth (80th Patriarch).", priority: 5},
    { date: "Paona 5", feast: "The Departure of St. James of the East.", priority: 5},
    { date: "Paona 5", feast: "The Martyrdom of Sts. Anba Bshay (Ebsoy) and Anba Botros (Peter).", priority: 5},
    { date: "Paona 5", feast: "The Commemoration of the Consecration of the church of St. Boctor (Victor) in the region of Sho.", priority: 5},
    { date: "Paona 6", feast: "The Departure of Pope Yoannis the Nineteenth, 113th Patriarch of Alexandria.", priority: 5},
    { date: "Paona 6", feast: "The Martyrdom of Sts. Apakir, John, Ptolemy and Philip.", priority: 5},
    { date: "Paona 7", feast: "The Martyrdom of St. Abaskhiroun the Soldier.", priority: 5},
    { date: "Paona 8", feast: "The Commemoration of the Consecration of the Church of the Virgin Lady known as El-Mahammah.", priority: 5},
    { date: "Paona 8", feast: "The Commemoration of St. Tamada and her children, and Armenius and his mother.", priority: 5},
    { date: "Paona 8", feast: "The Martyrdom of George (Girgis) the new martyr.", priority: 5},
    { date: "Paona 9", feast: "The Martyrdom of St. Claudius.", priority: 5},
    { date: "Paona 9", feast: "The Commemoration of the Consecration of the Altar of the Forty Martyrs in Alexandria.", priority: 5},
    { date: "Paona 10", feast: "The Martyrdom of St. Dabamon.", priority: 5},
    { date: "Paona 10", feast: "The Commemoration of the Closing of the Pagan Temples and Opening of the Churches.", priority: 5},
    { date: "Paona 10", feast: "The Departure of St. Yoannis the 16th, the 103rd Pope of Alexandria.", priority: 5},
    { date: "Paona 10", feast: "The Enthronement of Pope Demitrius the Second, the 111th Patriarch of Alexandria.", priority: 5},
    { date: "Paona 11", feast: "The Martyrdom of St. Claudius.", priority: 5},
    { date: "Paona 11", feast: "The Commemoration of the Consecration of the Altar of the Forty Martyrs in Alexandria.", priority: 5},
    { date: "Paona 12", feast: "The Commemoration of Archangel Michael.", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Paona 12", feast: "The Departure of St. Justus, the Sixth Pope of the See of St. Mark.", priority: 5},
    { date: "Paona 12", feast: "The Departure of St. Kyrillos the Second, the 67th Pope of Alexandria.", priority: 5},
    { date: "Paona 12", feast: "The Departure of St. Euphemia.", priority: 5},
    { date: "Paona 13", feast: "The Departure of St. John, Bishop of Jerusalem.", priority: 5},
    { date: "Paona 13", feast: "The Commemoration of the Archangel Gabriel, the Announcer of Daniel the Prophet.", priority: 5, type: ["Heavenly"], saintName: "Archangel Gabriel"},
    { date: "Paona 14", feast: "The Departure of Pope Yoannis the Nineteenth, 113th Patriarch of Alexandria.", priority: 5},
    { date: "Paona 14", feast: "The Martyrdom of Sts. Apakir, John, Ptolemy and Philip.", priority: 5},
    { date: "Paona 15", feast: "The Turning Over of the Relics of the Great St. Mark the Evangelist by the hand of Pope Paul the Sixth, Pope of Rome.", priority: 5, type: ["Apostle","Martyr"], saintName: "St. Mark the Evangelist"},
    { date: "Paona 15", feast: "The Consecration of the Church of Mari Mina at Maryut.", priority: 5, type: ["Martyr"], saintName: "St. Mina the Wonder Worker"},
    { date: "Paona 16", feast: "The Departure of St. Abba Nofer the Anchorite.", priority: 5},
    { date: "Paona 17", feast: "The Return of the Relics of the Great St. Mark to the New St. Mark Cathedral.", priority: 5},
    { date: "Paona 17", feast: "The Departure of St. Latsoun El-Bahnasawy.", priority: 5},
    { date: "Paona 18", feast: "The Inauguration of the New St. Mark Cathedral in the Monastery of Anba Rowais.", priority: 5},
    { date: "Paona 18", feast: "The Departure of St. Damianos, 35th Pope of Alexandria.", priority: 5},
    { date: "Paona 19", feast: "The First Pontifical Liturgy in the New St. Mark Cathedral in the Monastery of Anba Rowais.", priority: 5},
    { date: "Paona 19", feast: "The Departure of Pope Archelaus, the Eighteenth Pope of Alexandria.", priority: 5},
    { date: "Paona 19", feast: "The Martyrdom of St. George (Girgis) known as El-Mezahem.", priority: 5},
    { date: "Paona 19", feast: "The Martyrdom of St. Bishai Anoub.", priority: 5},
    { date: "Paona 20", feast: "The Departure of Elisha, the Prophet.", priority: 5},
    { date: "Paona 21", feast: "The Commemoration of the First Church for The Virgin Mary in the city of Philippi.", priority: 5},
    { date: "Paona 21", feast: "The Martyrdom of St. Timothy of Memphis (El-Masry).", priority: 5},
    { date: "Paona 21", feast: "The Departure of St. Cedron (Kardonos), the Fourth Patriarch of Alexandria.", priority: 5},
    { date: "Paona 22", feast: "The Consecration of the Church of Sts. Cosmas, Damian, Their Mother, and Brothers.", priority: 5, type: ["Martyr"], saintName: "Sts. Cosmas & Damian"},
    { date: "Paona 23", feast: "The Departure of St. Abba Noub the Confessor.", priority: 5},
    { date: "Paona 24", feast: "Martyrdom of the Great Saint Anba Moses the Strong", priority: 5, type: ["Martyr"], saintName: "St. Moses the Strong"}, 
    { date: "Paona 25", feast: "The Martyrdom of St. Jude, one of the Seventy Disciples.", priority: 5},
    { date: "Paona 25", feast: "The Departure of St. Peter the Fourth, 34th Pope of Alexandria.", priority: 5},
    { date: "Paona 26", feast: "The Departure of the Great Prophet Joshua Son of Nun.", priority: 5},
    { date: "Paona 26", feast: "The Consecration of the Church of Archangel Gabriel.", priority: 5, type: ["Heavenly"], saintName: "Archangel Gabriel"},
    { date: "Paona 27", feast: "The Martyrdom of St. Ananias, the Apostle.", priority: 5, type: ["Apostle", "Martyr"], saintName: "Any Apostle"},
    { date: "Paona 27", feast: "The Martyrdom of St. Thomas of Shentalet.", priority: 5},
    { date: "Paona 28", feast: "The Departure of St. Theodosius, 33rd Pope of Alexandria.", priority: 5},
    { date: "Paona 28", feast: "The Commemoration of the Consecration of the Church of Anba Sarabamoun, Bishop of Nikios.", priority: 5},
    { date: "Paona 29", feast: "The Martyrdom of the Seven Ascetic Saints in Tounar Mount.", priority: 5},
    { date: "Paona 29", feast: "The Martyrdom of Sts. Abba Hour and his Mother Theodora.", priority: 5},
    { date: "Paona 30", feast: "The Nativity of St. John, the Baptist.", priority: 5, type: ["Heavenly"], saintName: "St. John the Baptist"},
    { date: "Epip 1", feast: "The Martyrdom of Saint Febronia the Ascetic.", priority: 5},
    { date: "Epip 1", feast: "The Departure of Saints Bioukha and Tayaban (Banayen) the priests.", priority: 5},
    { date: "Epip 2", feast: "The Departure of St. Thaddaeus, the Apostle.", priority: 5, type: ["Apostle", "Martyr"], saintName: "Any Apostle"},
    { date: "Epip 3", feast: "The Departure of St. Kyrillos (Cyril) the First, the Twenty- Fourth Pope of Alexandria.", priority: 5},
    { date: "Epip 3", feast: "The Departure of St. Celestine, Pope of Rome.", priority: 5},
    { date: "Epip 4", feast: "The Commemoration of the Relocation of the Relics of Sts. Apakir and John.", priority: 5},
    { date: "Epip 5", feast: "The Martyrdom of Sts. Peter and Paul, the Apostles.", priority: 5, type: ["Martyr" , "Apostle"], saintName: "St. Peter & St. Paul"},
    { date: "Epip 6", feast: "The Martyrdom of St. Aoulimpas, the Apostle.", priority: 5, type: ["Apostle", "Martyr"], saintName: "Any Apostle"},
    { date: "Epip 6", feast: "The Martyrdom of St. Theodosia and her companions.", priority: 5},
    { date: "Epip 7", feast: "The Departure of St. Shenouda (Shenoute), the Archimandrite.", priority: 5, type: ["Saint"], saintName: "St. Shenouda the Archimandrite"},    
    { date: "Epip 7", feast: "The Martyrdom of St Ignatius, Bishop of Antioch, in Rome.", priority: 5},
    { date: "Epip 8", feast: "The Departure of St. Anba Bishoy.", priority: 5},
    { date: "Epip 8", feast: "The Martyrdom of St. Piroou and St. Athom.", priority: 5},
    { date: "Epip 8", feast: "The Martyrdom of St. Balanah, the Priest.", priority: 5},
    { date: "Epip 8", feast: "The Martyrdom of St. Epime (Pimanon).", priority: 5},
    { date: "Epip 8", feast: "The Departure of Cyrus (Karas), brother of Emperor Theodosius.", priority: 5},
    { date: "Epip 9", feast: "The Martyrdom of St. Simon Cleophas, the Apostle.", priority: 5, type: ["Apostle", "Martyr"], saintName: "Any Apostle"},
    { date: "Epip 9", feast: "The Departure of St. Cladianus (Celadion), the Ninth Pope of the See of St. Mark.", priority: 5},
    { date: "Epip 10", feast: "The Martyrdom of St. Theodore, Bishop of Pentapolis.", priority: 5},
    { date: "Epip 10", feast: "The Martyrdom of St. Theodore, Bishop of Corinth, and his companions.", priority: 5},
    { date: "Epip 10", feast: "The Departure of Anba Gabriel VII, 95th Pope of Alexandria.", priority: 5},
    { date: "Epip 11", feast: "The Martyrdom of Sts. John and Simon, his cousin.", priority: 5},
    { date: "Epip 11", feast: "The Departure of St. Isaiah, the hermit.", priority: 5},
    { date: "Epip 12", feast: "The Commemoration of Archangel Michael.", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Epip 12", feast: "The Martyrdom of St. Abba Hour El-Siriakousy.", priority: 5},
    { date: "Epip 13", feast: "The Departure of St. Pisentius, Bishop of Qift.", priority: 5},
    { date: "Epip 13", feast: "The Martyrdom of St. Apamon of Toukh.", priority: 5},
    { date: "Epip 13", feast: "The Martyrdom of St. Abba Shenoute, during the Early Arab Rule.", priority: 5},
    { date: "Epip 14", feast: "The Martyrdom of St. Procopius (Proconius) of Jerusalem.", priority: 5},
    { date: "Epip 14", feast: "The Departure of St. Peter the Fifth, 83rd Patriarch of Alexandria.", priority: 5},
    { date: "Epip 15", feast: "The Departure of St. Ephraem El-Soriani (The Syrian).", priority: 5},
    { date: "Epip 15", feast: "The Martyrdom of St. Cyriacus and St. Julietta His Mother.", priority: 5},
    { date: "Epip 15", feast: "The Martyrdom of St. Horesius (Harsios) of Soul.", priority: 5},
    { date: "Epip 16", feast: "The Departure of St. John, of the Golden Gospel.", priority: 5},
    { date: "Epip 16", feast: "The Recovery of the Holy Relics of St. George, the Prince of the Martyrs.", priority: 5, type: ["Martyr"], saintName: "St. George, Prince of the Martyrs"},
    { date: "Epip 17", feast: "The Martyrdom of St. Euphemia.", priority: 5},
    { date: "Epip 18", feast: "The Martyrdom of St. James the Apostle, Bishop of Jerusalem.", priority: 5, type: ["Apostle", "Martyr"], saintName: "Any Apostle"},
    { date: "Epip 19", feast: "The Martyrdom of Sts. Bidaba, Bishop of Qift, Anba Andrew, and Anba Christodoulas.", priority: 5},
    { date: "Epip 19", feast: "The Martyrdom of St. Pantaleemon, the Physician.", priority: 5},
    { date: "Epip 19", feast: "The Departure of Pope Youanis X, 85th Patriarch of Alexandria.", priority: 5},
    { date: "Epip 20", feast: "The Martyrdom of St. Theodore of Shotep.", priority: 5, type: ["Martyr"], saintName: "St. Theodore El-Shotbe"},
    { date: "Epip 21", feast: "The Commemoration of the Lady, the Virgin Mary.", priority: 5},
    { date: "Epip 21", feast: "The Departure of St. Sisinnios (Sosenius), the Eunich.", priority: 5},
    { date: "Epip 22", feast: "The Commemoration of the Martyrdom of St. Macarius, the Son of Basilides (Wasilides) the Minister.", priority: 5},        
    { date: "Epip 22", feast: "The Commemoration of the Martyrdom of St. Leontius of Tripoli (Lawendius).", priority: 5},
    { date: "Epip 23", feast: "The Martyrdom of St. Longinus the Soldier.", priority: 5},
    { date: "Epip 23", feast: "The Martyrdom of St. Marina, of Antioch.", priority: 5, type: ["Female Martyr"], saintName: "St. Marina the Martyrcd"},
    { date: "Epip 24", feast: "The Martyrdom of St. Abanoub of Nehis.", priority: 5, type: ["Martyr"], saintName: "St. Abanoub of Nehis"},
    { date: "Epip 24", feast: "The Departure of St. Simeon the First, 42nd Pope of Alexandria.", priority: 5},
    { date: "Epip 25", feast: "The Departure of St. Thecla.", priority: 5},
    { date: "Epip 25", feast: "The Martyrdom of the Saint Abba Isaac.", priority: 5},
    { date: "Epip 25", feast: "The Martyrdom of St. Hilaria.", priority: 5},
    { date: "Epip 25", feast: "The Martyrdom of Sts. Thecla and Mouji.", priority: 5},
    { date: "Epip 25", feast: "The Martyrdom of St. Antonius (Anthony) of Beba.", priority: 5},
    { date: "Epip 25", feast: "The Martyrdom of St. Abakragoun.", priority: 5},
    { date: "Epip 25", feast: "The Martyrdom of St. Domadius El-Souriani (The Syrian).", priority: 5},
    { date: "Epip 25", feast: "The Consecration of the Church of St. Philopatir Mercorios.", priority: 5, type: ["Martyr"], saintName: "St. Philopatir Mercorios"},
    { date: "Epip 25", feast: "The Departure of St. Palamon, the Father of the Monks. ", priority: 5},
    { date: "Epip 26", feast: "Repose of St. Joseph the Carpentar", priority: 5, type: ["Saint"], saintName: "St. Joseph the Carpentar"},
    { date: "Epip 26", feast: "Repose of Timothy I, Pope of Alexanderia    ", priority: 5},
    { date: "Epip 27", feast: "The Consecration of the Church of St. Abba Fam.", priority: 5},
    { date: "Epip 27", feast: "The Martyrdom of St. Apamon (Abba Amoun).", priority: 5},
    { date: "Epip 28", feast: "The Departure of St. Mary Magdalene.", priority: 5},
    { date: "Epip 29", feast: "The Commemoration of the Translocation of the Relics of St. Andrew, the Apostle.", priority: 5, type: ["Apostle","Martyr"], saintName: "Any Apostle"},
    { date: "Epip 29", feast: "The Martyrdom of St. Ouarshenoufa (Warshenofius).", priority: 5},
    { date: "Epip 30", feast: "The Martyrdom of Sts. Mercurius and Ephraem.", priority: 5},
    { date: "Mesore 1", feast: "The Martyrdom of St. Apoli, Son of Justus.", priority: 5},
    { date: "Mesore 1", feast: "The Departure of St. Kyrillos V (Cyril), 112th Pope of Alexandria.", priority: 5},
    { date: "Mesore 2", feast: "The Departure of St. Pa'esa (Athanasia).", priority: 5},
    { date: "Mesore 3", feast: "The Relocation of the Body of St. Simon (Simeon) the Stylite to the city of Antioch.", priority: 5},
    { date: "Mesore 3", feast: "The Departure of Pope Abriamus (Primus), Fifth Patriarch of Alexandria.", priority: 5},
    { date: "Mesore 4", feast: "Departure of Hezekiah the King", priority: 5},
    { date: "Mesore 4", feast: "Consecration of the Church of the Great St. Anthony", priority: 5, type: ["Saint"], saintName: "St. Anthony the Great"},
    { date: "Mesore 5", feast: "The Departure of St. John the Soldier.", priority: 5},
    { date: "Mesore 6", feast: "The Martyrdom of St. Julietta.", priority: 5},
    { date: "Mesore 7", feast: "The Annunciation of St. Joachim with the Birth of the Virgin Mary.", priority: 5},
    { date: "Mesore 7", feast: "The Departure of St. Timothy II (Timotheos), 26th Pope of Alexandria.", priority: 5},
    { date: "Mesore 8", feast: "The Martyrdom of the Sts. Lazarus, Salomi, His Wife, and Their Children.", priority: 5},
    { date: "Mesore 8", feast: "The Confession of St. Peter, the Apostle, that Christ is the Son of the Living God.", priority: 5, type: ["Apostle","Martyr"], saintName: "St. Peter & St. Paul"},
    { date: "Mesore 9", feast: "Martyrdom of St.Ari, the Priest of Shatanouf .", priority: 5},
    { date: "Mesore 10", feast: "The Martyrdom of St. Matra.", priority: 5},
    { date: "Mesore 10", feast: "The Martyrdom of St. Pigebs (Bekhebs).", priority: 5},
    { date: "Mesore 11", feast: "The Departure of St. Moisis, Bishop of Ouseem.", priority: 5},
    { date: "Mesore 12", feast: "The Commemoration of the Honorable Archangel Michael.", priority: 5, type: ["Heavenly"], saintName: "Archangel Michael"},
    { date: "Mesore 12", feast: "The Reign of the Righteous Emperor Constantine, the Great.", priority: 5},
    { date: "Mesore 13", feast: "The Feast of Transfiguration of Our Lord on Mount Tabor.", priority: 5},
    { date: "Mesore 14", feast: "The Commemoration of the Great Sign, the Lord had Manifested During the Papacy of St. Theophilus.", priority: 5},       
    { date: "Mesore 15", feast: "The Commemoration of the Departure of St. Mary Known as Marina, the Ascetic.", priority: 5},
    { date: "Mesore 16", feast: "The Assumption of the Body of the Pure Virgin St. Mary.", priority: 5},
    { date: "Mesore 16", feast: "The Departure of St. Mattias IV (Mattheos), 102nd Patriarch of Alexandria.", priority: 5},
    { date: "Mesore 17", feast: "The Martyrdom of St. James the Soldier.", priority: 5},
    { date: "Mesore 18", feast: "The Departure of St. Alexander, Patriarch of Constantinople.", priority: 5},
    { date: "Mesore 18", feast: "The Martyrdom of St. Eudaemon, of Armant (El-Armanti).", priority: 5},
    { date: "Mesore 19", feast: "The Translocation of the Body of St. Macarius to His Monastery in Scetis.", priority: 5, type: ["Saint"], saintName: "St. Macarius the Great"},    
    { date: "Mesore 20", feast: "The Martyrdom of the Seven Young Men of Ephesus.", priority: 5},
    { date: "Mesore 21", feast: "The Commemoration of the Virgin, the Mother of God", priority: 5},
    { date: "Mesore 21", feast: "The Departure of St. Irene (Eirene)", priority: 5},
    { date: "Mesore 22", feast: "The Departure of Micah, the Prophet.", priority: 5},
    { date: "Mesore 22", feast: "The Martyrdom of St. Hadid.", priority: 5},
    { date: "Mesore 23", feast: "The Martyrdom of Thirty Thousand Christians in Alexandria.", priority: 5},
    { date: "Mesore 23", feast: "The Martyrdom of St. Damian in Antioch.", priority: 5},
    { date: "Mesore 24", feast: "The Departure of St. Takla Haymanot, the Ethiopian.", priority: 5, type: ["Saint"], saintName: "St. Takla Haymanot"},  
    { date: "Mesore 24", feast: "The Departure of St. Thomas, Bishop of Mar'ash (Syria).", priority: 5},
    { date: "Mesore 25", feast: "The Departure of St. Bessarion, the Great.", priority: 5},
    { date: "Mesore 25", feast: "The Departure of St. Macarius III, 114th Pope of Alexandria.", priority: 5},
    { date: "Mesore 26", feast: "The Martyrdom of St. Moses (Moisees) and his Sister Sarah.", priority: 5},
    { date: "Mesore 26", feast: "The Martyrdom of St. Agabius, the Soldier, and his Sister Thecla.", priority: 5},
    { date: "Mesore 27", feast: "The Martyrdom of Sts. Benjamin and his Sister Eudexia.", priority: 5},
    { date: "Mesore 27", feast: "The Martyrdom of St. Mary, the Armenian.", priority: 5},
    { date: "Mesore 28", feast: "Our father Abraham", priority: 5, type: ["Patriarch"], saintName: "The Patriarch Abraham, Isaac, and Jacob"},      
    { date: "Mesore 28", feast: "Our father Isaac", priority: 5, type: ["Patriarch"], saintName: "The Patriarch Abraham, Isaac, and Jacob"},    
    { date: "Mesore 28", feast: "The father of the Tribes Jacob", priority: 5, type: ["Patriarch"], saintName: "The Patriarch Abraham, Isaac, and Jacob"},  
    { date: "Mesore 29", feast: "The Martyrdom of Sts. Athanasius, the Bishop, Gerasimus (Jarasimus), and Theodotus.", priority: 5},
    { date: "Mesore 29", feast: "The Arrival of the Holy Relic of St. John, the Short, to the Wilderness of Scetis.", priority: 5, type: ["Saint", "Event"], saintName: "St. John the Short"},   
    { date: "Mesore 30", feast: "The Departure of St. Malachi, the Prophet.", priority: 5},
    { date: "Nasie 1", feast: "The Departure of St. Eutychus.", priority: 5},
    { date: "Nasie 1", feast: "The Martyrdom of St. Pishay (Abshai), the Antiochian.", priority: 5},
    { date: "Nasie 2", feast: "The Departure of St. Titus, the Apostle.", priority: 5, type: ["Apostle", "Saint"], saintName: "Any Apostle"},
    { date: "Nasie 3", feast: "Commemoration of Archangel Raphael", priority: 5, type: ["Heavenly"], saintName: "Archangel Raphael"},
    { date: "Nasie 3", feast: "Martyrdom of St. Andrianus", priority: 5},
    { date: "Nasie 3", feast: "Departure of St. Yoannis XIV", priority: 5},
    { date: "Nasie 4", feast: "The Departure of St. Leparius, Bishop of Rome.", priority: 5},
    { date: "Nasie 4", feast: "The Departure of St. Poimen, the Hermit.", priority: 5},
    { date: "Nasie 5", feast: "The Departure of St. James, Bishop of Misre.", priority: 5},
    { date: "Nasie 5", feast: "The Departure of the Righteous Amos, the Prophet.", priority: 5},
    { date: "Nasie 5", feast: "The Departure of St. Barsoma, the 'Naked'.", priority: 5, type: ["Saint"], saintName: "St. Barsoma the Naked"},  
    { date: "Nasie 5", feast: "The Departure of St. Yoannis XV, 99th Pope of Alexandria.", priority: 5},
];